### ISSUE TITLE
Very nice work, just two points

### ISSUE THREAD

**Issue by Elias011** [JiDarwish/JavaScript2#1]
Hello Ji 
Very nice work 
Simple and clear code with comments to explain everything.
I just have two small points:
-	First <"div"> you created you can remove it if you don’t need it
-	Could you explain to me that which element you mean by “*” in the first tag in your CSS page. I don’t understand it

**Comment by JiDarwish** [comment]
Thanks for the feedback Elias!
For the first point yes you are totally right, I was thinking about creating a header beside the logo, don't know why I didn't though but if I had created it I would've needed the div but now I don't need it anymore.
Second point yes the * represents everything, it's like the whole HTML.
